// <auto-generated />
using System;
using Gestaurante.Models.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Gestaurante.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260330103029_AddFacturaBillingSnapshotAndCustomerFiscalFields")]
    partial class AddFacturaBillingSnapshotAndCustomerFiscalFields
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Gestaurante.Models.Entities.Categoria", b =>
                {
                    b.Property<Guid>("IdCategoria")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasComment("Descripción de la categoría");

                    b.HasKey("IdCategoria")
                        .HasName("PK_Categorias");

                    b.ToTable("Categorias");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.ClienteDireccion", b =>
                {
                    b.Property<Guid>("IdClienteDireccion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Alias")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid>("IdUsuarioCliente")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Notes")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<string>("PostalCode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Province")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdClienteDireccion")
                        .HasName("PK_ClienteDirecciones");

                    b.HasIndex("IdUsuarioCliente");

                    b.ToTable("ClienteDirecciones");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.ClienteEmailVerification", b =>
                {
                    b.Property<Guid>("IdClienteEmailVerification")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer");

                    b.Property<string>("CodeHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdUsuarioCliente")
                        .HasColumnType("uuid");

                    b.HasKey("IdClienteEmailVerification")
                        .HasName("PK_ClienteEmailVerifications");

                    b.HasIndex("IdUsuarioCliente", "ExpiresAt");

                    b.ToTable("ClienteEmailVerifications");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.ClienteMetodoPago", b =>
                {
                    b.Property<Guid>("IdClienteMetodoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<int>("ExpMonth")
                        .HasColumnType("integer");

                    b.Property<int>("ExpYear")
                        .HasColumnType("integer");

                    b.Property<string>("HolderName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<Guid>("IdUsuarioCliente")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsDefault")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("Last4")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("character varying(4)");

                    b.Property<string>("MockPaymentToken")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.HasKey("IdClienteMetodoPago")
                        .HasName("PK_ClienteMetodosPago");

                    b.HasIndex("IdUsuarioCliente");

                    b.ToTable("ClienteMetodosPago");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.DetallePedido", b =>
                {
                    b.Property<Guid>("IdDetallePedido")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<int>("Cantidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaCancelacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdPedido")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdPlato")
                        .HasColumnType("uuid");

                    b.Property<double>("PrecioUnitario")
                        .HasColumnType("decimal(10,2)");

                    b.HasKey("IdDetallePedido")
                        .HasName("PK_DetallePedido");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdPlato");

                    b.ToTable("DetallesPedido");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Empleado", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DNI")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("ImageURL")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<string>("NUSS")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("SecondLastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id")
                        .HasName("PK_Empleados");

                    b.HasIndex("DNI")
                        .IsUnique();

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("NUSS")
                        .IsUnique();

                    b.ToTable("Empleados");

                    b.HasDiscriminator<int>("Tipo");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Factura", b =>
                {
                    b.Property<Guid>("NumeroFactura")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<string>("BillingCity")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("Madrid");

                    b.Property<string>("BillingDocument")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("00000000X");

                    b.Property<string>("BillingEmail")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("anonimo@gestaurante.local");

                    b.Property<string>("BillingName")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasDefaultValue("Cliente anónimo");

                    b.Property<string>("BillingPhone")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasDefaultValue("600000000");

                    b.Property<string>("BillingPostalCode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("28000");

                    b.Property<string>("BillingProvince")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("Madrid");

                    b.Property<string>("BillingStreet")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("Calle Falsa 123");

                    b.Property<int?>("CanalPedido")
                        .HasColumnType("integer");

                    b.Property<double>("Descuento")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(5,2)")
                        .HasDefaultValue(0.0);

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime>("FechaFactura")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("IdMesa")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdPedido")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUsuarioCliente")
                        .HasColumnType("uuid");

                    b.Property<double>("PrecioTotal")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0.0);

                    b.HasKey("NumeroFactura")
                        .HasName("PK_Facturas");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdPedido");

                    b.HasIndex("IdUsuarioCliente");

                    b.ToTable("Facturas");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Ingrediente", b =>
                {
                    b.Property<Guid>("IdIngrediente")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<bool>("Alergenico")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Indica si el ingrediente es alergénico");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Indica si el ingrediente está disponible para usar");

                    b.Property<string>("Imagen")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("")
                        .HasComment("URL de la imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdIngrediente")
                        .HasName("PK_Ingredientes");

                    b.ToTable("Ingredientes");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Mesa", b =>
                {
                    b.Property<Guid>("IdMesa")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(4);

                    b.Property<bool>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasComment("Estado de la mesa: true=Disponible, false=Ocupada");

                    b.Property<string>("Ubicacion")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("Interior")
                        .HasComment("Ubicación física de la mesa en el restaurante");

                    b.HasKey("IdMesa")
                        .HasName("PK_Mesas");

                    b.ToTable("Mesas");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.MesaPublicSession", b =>
                {
                    b.Property<Guid>("IdMesaPublicSession")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("IdMesa")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("IdMesaPublicSession")
                        .HasName("PK_MesaPublicSessions");

                    b.HasIndex("IdMesa", "IsActive", "ExpiresAt");

                    b.ToTable("MesaPublicSessions");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Pedido", b =>
                {
                    b.Property<Guid>("IdPedido")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<int>("CanalPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ClienteDireccionSnapshot")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(400)
                        .HasColumnType("character varying(400)")
                        .HasDefaultValue("");

                    b.Property<string>("ClienteEmail")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("");

                    b.Property<string>("ClienteNombre")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasDefaultValue("");

                    b.Property<string>("ClienteTelefono")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)")
                        .HasDefaultValue("");

                    b.Property<int>("Estado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("EstadoPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<DateTime?>("FechaModificacion")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaPedido")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<Guid?>("IdFactura")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdMesa")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdMesaPublicSession")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("IdUsuarioCliente")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasDefaultValue("");

                    b.Property<int>("TipoEntrega")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("IdPedido")
                        .HasName("PK_Pedidos");

                    b.HasIndex("IdFactura");

                    b.HasIndex("IdMesa");

                    b.HasIndex("IdMesaPublicSession");

                    b.HasIndex("IdUsuarioCliente");

                    b.ToTable("Pedidos");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Plato", b =>
                {
                    b.Property<Guid>("IdPlato")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("Descripción del plato");

                    b.Property<bool>("Disponible")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasComment("Disponibilidad del plato");

                    b.Property<Guid>("IdCategoria")
                        .HasColumnType("uuid");

                    b.Property<string>("Imagen")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasComment("URL de la imagen");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasComment("Nombre del plato");

                    b.Property<Guid?>("PlatoIdPlato")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Precio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("decimal(10,2)")
                        .HasDefaultValue(0m);

                    b.Property<DateTime?>("UpdatedAt")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdPlato")
                        .HasName("PK_Platos");

                    b.HasIndex("IdCategoria");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.HasIndex("PlatoIdPlato");

                    b.ToTable("Platos");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.PlatoIngrediente", b =>
                {
                    b.Property<Guid>("IdPlato")
                        .HasColumnType("uuid");

                    b.Property<Guid>("IdIngrediente")
                        .HasColumnType("uuid");

                    b.HasKey("IdPlato", "IdIngrediente")
                        .HasName("PK_PlatoIngrediente");

                    b.HasIndex("IdIngrediente");

                    b.ToTable("PlatoIngrediente");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.UsuarioCliente", b =>
                {
                    b.Property<Guid>("IdUsuarioCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("BillingCity")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("");

                    b.Property<string>("BillingPostalCode")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<string>("BillingProvince")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasDefaultValue("");

                    b.Property<string>("BillingStreet")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasDefaultValue("");

                    b.Property<string>("Cif")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasDefaultValueSql("NOW() AT TIME ZONE 'UTC'");

                    b.Property<string>("Dni")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)")
                        .HasDefaultValue("");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("EmailVerificado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<string>("FiscalName")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)")
                        .HasDefaultValue("");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("IdUsuarioCliente")
                        .HasName("PK_UsuariosCliente");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("UsuariosCliente");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Administrador", b =>
                {
                    b.HasBaseType("Gestaurante.Models.Entities.Empleado");

                    b.HasDiscriminator().HasValue(0);
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Camarero", b =>
                {
                    b.HasBaseType("Gestaurante.Models.Entities.Empleado");

                    b.Property<int>("NumeroMesas")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue(1);
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Cocinero", b =>
                {
                    b.HasBaseType("Gestaurante.Models.Entities.Empleado");

                    b.HasDiscriminator().HasValue(2);
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Repartidor", b =>
                {
                    b.HasBaseType("Gestaurante.Models.Entities.Empleado");

                    b.HasDiscriminator().HasValue(3);
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.ClienteDireccion", b =>
                {
                    b.HasOne("Gestaurante.Models.Entities.UsuarioCliente", null)
                        .WithMany("Direcciones")
                        .HasForeignKey("IdUsuarioCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.ClienteEmailVerification", b =>
                {
                    b.HasOne("Gestaurante.Models.Entities.UsuarioCliente", null)
                        .WithMany()
                        .HasForeignKey("IdUsuarioCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.ClienteMetodoPago", b =>
                {
                    b.HasOne("Gestaurante.Models.Entities.UsuarioCliente", null)
                        .WithMany("MetodosPago")
                        .HasForeignKey("IdUsuarioCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.DetallePedido", b =>
                {
                    b.HasOne("Gestaurante.Models.Entities.Pedido", null)
                        .WithMany("DetallesPedido")
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestaurante.Models.Entities.Plato", null)
                        .WithMany()
                        .HasForeignKey("IdPlato")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Factura", b =>
                {
                    b.HasOne("Gestaurante.Models.Entities.Mesa", null)
                        .WithMany()
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gestaurante.Models.Entities.Pedido", null)
                        .WithMany()
                        .HasForeignKey("IdPedido")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gestaurante.Models.Entities.UsuarioCliente", null)
                        .WithMany()
                        .HasForeignKey("IdUsuarioCliente")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.MesaPublicSession", b =>
                {
                    b.HasOne("Gestaurante.Models.Entities.Mesa", null)
                        .WithMany()
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Pedido", b =>
                {
                    b.HasOne("Gestaurante.Models.Entities.Factura", null)
                        .WithMany()
                        .HasForeignKey("IdFactura")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gestaurante.Models.Entities.Mesa", null)
                        .WithMany()
                        .HasForeignKey("IdMesa")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gestaurante.Models.Entities.MesaPublicSession", null)
                        .WithMany()
                        .HasForeignKey("IdMesaPublicSession")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Gestaurante.Models.Entities.UsuarioCliente", null)
                        .WithMany()
                        .HasForeignKey("IdUsuarioCliente")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Plato", b =>
                {
                    b.HasOne("Gestaurante.Models.Entities.Categoria", "Categoria")
                        .WithMany("Platos")
                        .HasForeignKey("IdCategoria")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("FK_Platos_Categorias");

                    b.HasOne("Gestaurante.Models.Entities.Plato", null)
                        .WithMany("Platos")
                        .HasForeignKey("PlatoIdPlato");

                    b.Navigation("Categoria");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.PlatoIngrediente", b =>
                {
                    b.HasOne("Gestaurante.Models.Entities.Ingrediente", "Ingrediente")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("IdIngrediente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Gestaurante.Models.Entities.Plato", "Plato")
                        .WithMany("PlatoIngredientes")
                        .HasForeignKey("IdPlato")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ingrediente");

                    b.Navigation("Plato");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Categoria", b =>
                {
                    b.Navigation("Platos");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Ingrediente", b =>
                {
                    b.Navigation("PlatoIngredientes");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Pedido", b =>
                {
                    b.Navigation("DetallesPedido");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.Plato", b =>
                {
                    b.Navigation("PlatoIngredientes");

                    b.Navigation("Platos");
                });

            modelBuilder.Entity("Gestaurante.Models.Entities.UsuarioCliente", b =>
                {
                    b.Navigation("Direcciones");

                    b.Navigation("MetodosPago");
                });
#pragma warning restore 612, 618
        }
    }
}
